/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import comunicacion.StartVista;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Inicio extends javax.swing.JFrame implements StartVista{

    /**
     * Creates new form Inicio
     */
    String p = "p1";
    ImageIcon I;
    public Inicio() {
        initComponents();
        LabelEntrada.setVisible(false);
        PortEntrada.setVisible(false);
        LabelSalida.setVisible(false);
        PortSalida.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        LabelNombre = new javax.swing.JLabel();
        TextNombre = new javax.swing.JTextField();
        LabelIP = new javax.swing.JLabel();
        TextIP = new javax.swing.JTextField();
        LabelEntrada = new javax.swing.JLabel();
        PortEntrada = new javax.swing.JTextField();
        LabelSalida = new javax.swing.JLabel();
        PortSalida = new javax.swing.JTextField();
        ComboBoxOpc = new javax.swing.JComboBox<>();
        CheckBoxAvanzado = new javax.swing.JCheckBox();
        ButtonJugar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(320, 320));

        LabelNombre.setText("Nombre:");

        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });

        LabelIP.setText("IP:");

        LabelEntrada.setText("Puerto de entrada:");

        PortEntrada.setText("9000");

        LabelSalida.setText("Puerto de salida:");

        PortSalida.setText("9001");

        ComboBoxOpc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crear Partida", "Unirce a una partida" }));
        ComboBoxOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxOpcActionPerformed(evt);
            }
        });

        CheckBoxAvanzado.setText("Avanzado");
        CheckBoxAvanzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxAvanzadoActionPerformed(evt);
            }
        });

        ButtonJugar.setText("Jugar");
        ButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJugarActionPerformed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CheckBoxAvanzado)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonJugar))
                            .addComponent(ComboBoxOpc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelIP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextIP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PortEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelSalida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PortSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelIP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextIP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PortEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSalida)
                    .addComponent(PortSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(ComboBoxOpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBoxAvanzado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonJugar)
                        .addComponent(ButtonCancelar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreActionPerformed

    private void CheckBoxAvanzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxAvanzadoActionPerformed
        if(evt.getSource()==this.CheckBoxAvanzado){
            if(CheckBoxAvanzado.isSelected()){
                LabelEntrada.setVisible(true);
                PortEntrada.setVisible(true);
                LabelSalida.setVisible(true);
                PortSalida.setVisible(true);
            }
            else{
                LabelEntrada.setVisible(false);
                PortEntrada.setVisible(false);
                LabelSalida.setVisible(false);
                PortSalida.setVisible(false);
            }
        }
    }//GEN-LAST:event_CheckBoxAvanzadoActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void ButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJugarActionPerformed
       int band=0;
            try{
                if(this.TextNombre.getText().equalsIgnoreCase(""))
                    throw new ClassNotFoundException();
                band=1;
                if(this.TextIP.getText().equalsIgnoreCase("localhost")){

                }
                else{
                    String[] ip=this.TextIP.getText().split(".");
                    if(this.TextIP.getText().equalsIgnoreCase(""))
                        throw new ClassNotFoundException();
                    for(int x=0;x<3;x++)
                        for(int y=0;y<ip[x].length();y++)
                            if(Character.isDigit(ip[x].charAt(y)))
                                throw new Exception();
                }
                band=2;
                Integer.parseInt(this.PortEntrada.getText());
                if(this.PortEntrada.getText().equalsIgnoreCase(""))
                    throw new ClassNotFoundException();
                band=3;
                Integer.parseInt(this.PortSalida.getText());
                if(this.PortSalida.getText().equalsIgnoreCase(""))
                    throw new ClassNotFoundException();
                if(this.PortSalida.getText().equalsIgnoreCase(this.PortEntrada.getText()))
                    throw new ArithmeticException();

                crear(TextNombre.getText(), TextIP.getText(), 
                        Integer.parseInt(PortEntrada.getText()), 
                        Integer.parseInt(PortSalida.getText()), p);
            }
            catch(ArithmeticException e){
                JOptionPane.showMessageDialog(null,"Los puertos no pueden ser iguales. \nPorfavor cambia uno de los dos");
            }
            catch(ClassNotFoundException e){
                JOptionPane.showMessageDialog(null,"Procura no dejar espacios vacíos. \nToda la información es importante");
            }
            catch(Exception e){
                if(band==1)
                    JOptionPane.showMessageDialog(null,"Formato de IP incorrecto. \nej. 189.220.191.252");
                if(band==2)
                    JOptionPane.showMessageDialog(null,"Formato de puerto 1 incorrecto");
                if(band==3)
                    JOptionPane.showMessageDialog(null,"Formato de puerto 2 incorrecto");
            }
    }//GEN-LAST:event_ButtonJugarActionPerformed

    private void ComboBoxOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxOpcActionPerformed
        String obj=ComboBoxOpc.getSelectedItem().toString();
        if(obj.toString().equalsIgnoreCase("Crear Partida")){
            p="p1";
            PortEntrada.setText("9000");
            PortSalida.setText("9001");
        }
        if(obj.toString().equalsIgnoreCase("Unirce a una partida")){
            p="p2";
            PortEntrada.setText("9001");
            PortSalida.setText("9000");
        }
    }//GEN-LAST:event_ComboBoxOpcActionPerformed

    @Override
    public void crear(String nombre, String ip, int port1, int port2, String p){
        Tablero Tablero=new Tablero(nombre, ip, port1, port2, p);
        setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Inicio().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonJugar;
    private javax.swing.JCheckBox CheckBoxAvanzado;
    private javax.swing.JComboBox<String> ComboBoxOpc;
    private javax.swing.JLabel LabelEntrada;
    private javax.swing.JLabel LabelIP;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelSalida;
    private javax.swing.JTextField PortEntrada;
    private javax.swing.JTextField PortSalida;
    private javax.swing.JTextField TextIP;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
